### ISSUE TITLE
putting on ocaml.org as well?

### ISSUE THREAD

**Issue by avsm** [r6eve/japanese-ocaml-companies#2]
Once you have a list you are happy with, we would love to also have this on the main ocaml.org website if you like!

The full list is on http://ocaml.org/learn/companies.html, and can be edited at https://github.com/ocaml/ocaml.org.  Feel free to get in touch if I can help.

**Comment by r6eve** [comment]
Thank you for catching this.

I announce the information to Japanese companies using OCaml.

**Comment by avsm** [comment]
Wonderful! I'll close this issue as it's not a real problem, but feel free to get in touch if I can help (anil@recoil.org)
