### ISSUE TITLE
お手伝い

### ISSUE THREAD

**Issue by TImada** [r6eve/japanese-ocaml-companies#3]
日本で OCaml/ReasonML を利用している会社の中の人ではありませんが、縁あって1年間 OCaml Labs にて活動していました。ocaml.org への繋ぎや、その他出来ることがあればお手伝いいたします。

**Comment by r6eve** [comment]
ありがとうございます．その際には，是非頼らせて頂きます．

**Comment by TImada** [comment]
takayuki.imada@gmail.com へメールを頂ければと思います。
